services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: equipment-rental
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
